#!/bin/bash

# Packages
apm install 'Zen'
apm install 'atom-clock'
apm install 'atom-easy-jsdoc'
apm install 'atom-keyboard-macros-vim'
apm install 'atom-liquid-snippets'
apm install 'atom-ternjs'
apm install 'autoclose'
apm install 'autocomplete-modules'
apm install 'autocomplete-paths'
apm install 'busy-signal'
apm install 'double-tag'
apm install 'editorconfig'
apm install 'emmet'
apm install 'file-icons'
apm install 'highlight-selected'
apm install 'intentions'
apm install 'language-babel'
apm install 'language-dotenv'
apm install 'language-fish-shell'
apm install 'language-liquid'
apm install 'language-pug'
apm install 'language-viml'
apm install 'linter'
apm install 'linter-eslint'
apm install 'linter-js-standard'
apm install 'linter-stylelint'
apm install 'linter-ui-default'
apm install 'no-title-bar'
apm install 'persistent-undo'
apm install 'pigments'
apm install 'pretty-json'
apm install 'project-manager'
apm install 'relative-numbers'
apm install 'standard-formatter'
apm install 'termination'
apm install 'vim-mode-plus'
apm install 'vim-mode-plus-keymaps-for-surround'
apm install 'warn-before-quitting'

# Themes
apm install 'gruvbox'
